# Generated by Django 5.0.6 on 2024-11-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('cursus', models.TextField()),
                ('experience', models.TextField()),
                ('competence', models.TextField()),
                ('langue', models.TextField()),
                ('softskills', models.TextField()),
                ('motivation', models.TextField(default='ma motiavion')),
                ('reference', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_offre', models.CharField(max_length=255)),
                ('nom_entreprise', models.CharField(max_length=50)),
                ('activite', models.TextField()),
                ('missions', models.TextField()),
                ('profil', models.TextField()),
                ('reference', models.TextField()),
            ],
        ),
    ]
